language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

before_install:
  - chmod +x gradlew

before_script:
  - echo yes | android update sdk --no-ui --all --filter platform-tools,tools
  - echo yes | android update sdk --no-ui --all --filter build-tools-29.0.3
  - echo yes | android update sdk --no-ui --all --filter android-29

script:
  - ./gradlew clean test