# Workflow for Android CI debug build

name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew assembleDebug dokkaHtml"
    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: splashscreen/build/dokka/html
        TARGET_FOLDER: docs
        